name = "pluma"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Pluma"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "pluma-proto"
git = "https://github.com/provables/pluma-proto.git"

[[require]]
name = "leansqlite"
git = "https://github.com/leanprover/leansqlite.git"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "Pluma"

[[lean_exe]]
supportInterpreter = true
name = "pluma"
root = "Main"
needs = ["Pluma"]
