port = 7777
supervised = true
wait = true
foreground = true
db = "./tutorial.db"
#plugins = ["OEISLt.Plugins.Dummy"]

[[plugins]]
module = "OEISLt.Plugins.Dummy"
name = "Dummy.plugin"

[[plugins]]
module = "OEISLt.Plugins.Dummy"
name = "Dummy.plugin2"